import "./globals.css";
import LetterGlitch from '../components/LetterGlitch';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LetterGlitch className="fixed inset-0 w-full h-full -z-10 pointer-events-none" />
        {children}
      </body>
    </html>
  );
}
